import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@components/Header'
import clsx from 'clsx'

import 'react-toastify/dist/ReactToastify.css';

import { authOptions } from './api/auth/[...nextauth]/authOptions.config'
import { getServerSession } from 'next-auth'

import LoginPage from '@components/LoginPage'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'My Cloud',
    description: 'Generated by Milliax',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    const session = await getServerSession(authOptions)
    console.log(session)
    // if not logged in display login page
    if (!session) {
        // not logged in

        return (
            <html>
                <body className={clsx(
                    inter.className,
                    'h-[calc(100vh-3rem)]'
                )}>
                    {/* <Header /> */}
                    <LoginPage />
                </body>
            </html>
        )
    }

    return (
        <html lang="zh-tw">
            <body className={clsx(
                inter.className,
                'h-[calc(100vh-3rem)]'
            )}>
                <Header />
                {children}
            </body>
        </html>
    )
}
